# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Xiang/project/Embaded_project/2023/Lab_final_student/Lab_Final_PS/Lab_Final_PS.srcs/sources_1/bd/PS_PL_test/ip/PS_PL_test_rst_ps7_0_50M_0/PS_PL_test_rst_ps7_0_50M_0.xci
# IP: The module: 'PS_PL_test_rst_ps7_0_50M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Xiang/project/Embaded_project/2023/Lab_final_student/Lab_Final_PS/Lab_Final_PS.gen/sources_1/bd/PS_PL_test/ip/PS_PL_test_rst_ps7_0_50M_0/PS_PL_test_rst_ps7_0_50M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'PS_PL_test_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Xiang/project/Embaded_project/2023/Lab_final_student/Lab_Final_PS/Lab_Final_PS.gen/sources_1/bd/PS_PL_test/ip/PS_PL_test_rst_ps7_0_50M_0/PS_PL_test_rst_ps7_0_50M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'PS_PL_test_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Xiang/project/Embaded_project/2023/Lab_final_student/Lab_Final_PS/Lab_Final_PS.gen/sources_1/bd/PS_PL_test/ip/PS_PL_test_rst_ps7_0_50M_0/PS_PL_test_rst_ps7_0_50M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'PS_PL_test_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Xiang/project/Embaded_project/2023/Lab_final_student/Lab_Final_PS/Lab_Final_PS.srcs/sources_1/bd/PS_PL_test/ip/PS_PL_test_rst_ps7_0_50M_0/PS_PL_test_rst_ps7_0_50M_0.xci
# IP: The module: 'PS_PL_test_rst_ps7_0_50M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Xiang/project/Embaded_project/2023/Lab_final_student/Lab_Final_PS/Lab_Final_PS.gen/sources_1/bd/PS_PL_test/ip/PS_PL_test_rst_ps7_0_50M_0/PS_PL_test_rst_ps7_0_50M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'PS_PL_test_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Xiang/project/Embaded_project/2023/Lab_final_student/Lab_Final_PS/Lab_Final_PS.gen/sources_1/bd/PS_PL_test/ip/PS_PL_test_rst_ps7_0_50M_0/PS_PL_test_rst_ps7_0_50M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'PS_PL_test_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Xiang/project/Embaded_project/2023/Lab_final_student/Lab_Final_PS/Lab_Final_PS.gen/sources_1/bd/PS_PL_test/ip/PS_PL_test_rst_ps7_0_50M_0/PS_PL_test_rst_ps7_0_50M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'PS_PL_test_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
