# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/PS_PL_test/PS_PL_test.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PS_PL_test || ORIG_REF_NAME==PS_PL_test} -quiet] -quiet

# IP: bd/PS_PL_test/ip/PS_PL_test_NN_test_IO_0_0/PS_PL_test_NN_test_IO_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PS_PL_test_NN_test_IO_0_0 || ORIG_REF_NAME==PS_PL_test_NN_test_IO_0_0} -quiet] -quiet

# IP: bd/PS_PL_test/ip/PS_PL_test_axi_dma_0_0/PS_PL_test_axi_dma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PS_PL_test_axi_dma_0_0 || ORIG_REF_NAME==PS_PL_test_axi_dma_0_0} -quiet] -quiet

# IP: bd/PS_PL_test/ip/PS_PL_test_xbar_0/PS_PL_test_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PS_PL_test_xbar_0 || ORIG_REF_NAME==PS_PL_test_xbar_0} -quiet] -quiet

# IP: bd/PS_PL_test/ip/PS_PL_test_axi_mem_intercon_0/PS_PL_test_axi_mem_intercon_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PS_PL_test_axi_mem_intercon_0 || ORIG_REF_NAME==PS_PL_test_axi_mem_intercon_0} -quiet] -quiet

# IP: bd/PS_PL_test/ip/PS_PL_test_blk_mem_gen_0_0/PS_PL_test_blk_mem_gen_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PS_PL_test_blk_mem_gen_0_0 || ORIG_REF_NAME==PS_PL_test_blk_mem_gen_0_0} -quiet] -quiet

# IP: bd/PS_PL_test/ip/PS_PL_test_myip_v1_0_0_0/PS_PL_test_myip_v1_0_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PS_PL_test_myip_v1_0_0_0 || ORIG_REF_NAME==PS_PL_test_myip_v1_0_0_0} -quiet] -quiet

# IP: bd/PS_PL_test/ip/PS_PL_test_processing_system7_0_0/PS_PL_test_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PS_PL_test_processing_system7_0_0 || ORIG_REF_NAME==PS_PL_test_processing_system7_0_0} -quiet] -quiet

# IP: bd/PS_PL_test/ip/PS_PL_test_xbar_1/PS_PL_test_xbar_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PS_PL_test_xbar_1 || ORIG_REF_NAME==PS_PL_test_xbar_1} -quiet] -quiet

# IP: bd/PS_PL_test/ip/PS_PL_test_ps7_0_axi_periph_0/PS_PL_test_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PS_PL_test_ps7_0_axi_periph_0 || ORIG_REF_NAME==PS_PL_test_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/PS_PL_test/ip/PS_PL_test_rst_ps7_0_50M_0/PS_PL_test_rst_ps7_0_50M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PS_PL_test_rst_ps7_0_50M_0 || ORIG_REF_NAME==PS_PL_test_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/PS_PL_test/ip/PS_PL_test_auto_pc_0/PS_PL_test_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PS_PL_test_auto_pc_0 || ORIG_REF_NAME==PS_PL_test_auto_pc_0} -quiet] -quiet

# IP: bd/PS_PL_test/ip/PS_PL_test_auto_pc_1/PS_PL_test_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PS_PL_test_auto_pc_1 || ORIG_REF_NAME==PS_PL_test_auto_pc_1} -quiet] -quiet

# XDC: c:/Xiang/project/Embaded_project/2023/Lab_final_student/Lab_Final_PS/Lab_Final_PS.gen/sources_1/bd/PS_PL_test/PS_PL_test_ooc.xdc
