# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/NN_xdc.xdc

# Block Designs: bd/NN_bd/NN_bd.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==NN_bd || ORIG_REF_NAME==NN_bd} -quiet] -quiet

# IP: bd/NN_bd/ip/NN_bd_blk_mem_gen_1_0/NN_bd_blk_mem_gen_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==NN_bd_blk_mem_gen_1_0 || ORIG_REF_NAME==NN_bd_blk_mem_gen_1_0} -quiet] -quiet

# IP: bd/NN_bd/ip/NN_bd_blk_mem_gen_2_0/NN_bd_blk_mem_gen_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==NN_bd_blk_mem_gen_2_0 || ORIG_REF_NAME==NN_bd_blk_mem_gen_2_0} -quiet] -quiet

# IP: bd/NN_bd/ip/NN_bd_blk_mem_gen_0_1/NN_bd_blk_mem_gen_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==NN_bd_blk_mem_gen_0_1 || ORIG_REF_NAME==NN_bd_blk_mem_gen_0_1} -quiet] -quiet

# IP: bd/NN_bd/ip/NN_bd_blk_mem_gen_0_2/NN_bd_blk_mem_gen_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==NN_bd_blk_mem_gen_0_2 || ORIG_REF_NAME==NN_bd_blk_mem_gen_0_2} -quiet] -quiet

# IP: bd/NN_bd/ip/NN_bd_MP1_0_0/NN_bd_MP1_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==NN_bd_MP1_0_0 || ORIG_REF_NAME==NN_bd_MP1_0_0} -quiet] -quiet

# IP: bd/NN_bd/ip/NN_bd_ConV1_0_0/NN_bd_ConV1_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==NN_bd_ConV1_0_0 || ORIG_REF_NAME==NN_bd_ConV1_0_0} -quiet] -quiet

# IP: bd/NN_bd/ip/NN_bd_MUX_mem_out_0_0/NN_bd_MUX_mem_out_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==NN_bd_MUX_mem_out_0_0 || ORIG_REF_NAME==NN_bd_MUX_mem_out_0_0} -quiet] -quiet

# IP: bd/NN_bd/ip/NN_bd_FC_0_0/NN_bd_FC_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==NN_bd_FC_0_0 || ORIG_REF_NAME==NN_bd_FC_0_0} -quiet] -quiet

# IP: bd/NN_bd/ip/NN_bd_MP2_0_0/NN_bd_MP2_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==NN_bd_MP2_0_0 || ORIG_REF_NAME==NN_bd_MP2_0_0} -quiet] -quiet

# XDC: c:/Lab_final/lab_final _NN/lab_final.gen/sources_1/bd/NN_bd/NN_bd_ooc.xdc
