# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Lab_final/lab_final_PLPS/lab_final.srcs/sources_1/bd/Lab_final_bd/ip/Lab_final_bd_blk_rom_inimg_0/Lab_final_bd_blk_rom_inimg_0.xci
# IP: The module: 'Lab_final_bd_blk_rom_inimg_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Lab_final/lab_final_PLPS/lab_final.gen/sources_1/bd/Lab_final_bd/ip/Lab_final_bd_blk_rom_inimg_0/Lab_final_bd_blk_rom_inimg_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Lab_final_bd_blk_rom_inimg_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Lab_final/lab_final_PLPS/lab_final.srcs/sources_1/bd/Lab_final_bd/ip/Lab_final_bd_blk_rom_inimg_0/Lab_final_bd_blk_rom_inimg_0.xci
# IP: The module: 'Lab_final_bd_blk_rom_inimg_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Lab_final/lab_final_PLPS/lab_final.gen/sources_1/bd/Lab_final_bd/ip/Lab_final_bd_blk_rom_inimg_0/Lab_final_bd_blk_rom_inimg_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Lab_final_bd_blk_rom_inimg_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
