# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/Lab/Embedded_Deep_Neural_Network_Processing/Lab_final/lab_final/lab_final.srcs/sources_1/bd/NN_bd/ip/NN_bd_blk_mem_gen_1_0/NN_bd_blk_mem_gen_1_0.xci
# IP: The module: 'NN_bd_blk_mem_gen_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Lab/Embedded_Deep_Neural_Network_Processing/Lab_final/lab_final/lab_final.gen/sources_1/bd/NN_bd/ip/NN_bd_blk_mem_gen_1_0/NN_bd_blk_mem_gen_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'NN_bd_blk_mem_gen_1_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: E:/Lab/Embedded_Deep_Neural_Network_Processing/Lab_final/lab_final/lab_final.srcs/sources_1/bd/NN_bd/ip/NN_bd_blk_mem_gen_1_0/NN_bd_blk_mem_gen_1_0.xci
# IP: The module: 'NN_bd_blk_mem_gen_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Lab/Embedded_Deep_Neural_Network_Processing/Lab_final/lab_final/lab_final.gen/sources_1/bd/NN_bd/ip/NN_bd_blk_mem_gen_1_0/NN_bd_blk_mem_gen_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'NN_bd_blk_mem_gen_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
