# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/Lab_final_bd/Lab_final_bd.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Lab_final_bd || ORIG_REF_NAME==Lab_final_bd} -quiet] -quiet

# IP: bd/Lab_final_bd/ip/Lab_final_bd_axi_dma_0_0/Lab_final_bd_axi_dma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Lab_final_bd_axi_dma_0_0 || ORIG_REF_NAME==Lab_final_bd_axi_dma_0_0} -quiet] -quiet

# IP: bd/Lab_final_bd/ip/Lab_final_bd_xbar_0/Lab_final_bd_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Lab_final_bd_xbar_0 || ORIG_REF_NAME==Lab_final_bd_xbar_0} -quiet] -quiet

# IP: bd/Lab_final_bd/ip/Lab_final_bd_auto_pc_0/Lab_final_bd_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Lab_final_bd_auto_pc_0 || ORIG_REF_NAME==Lab_final_bd_auto_pc_0} -quiet] -quiet

# IP: bd/Lab_final_bd/ip/Lab_final_bd_axi_mem_intercon_0/Lab_final_bd_axi_mem_intercon_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Lab_final_bd_axi_mem_intercon_0 || ORIG_REF_NAME==Lab_final_bd_axi_mem_intercon_0} -quiet] -quiet

# IP: bd/Lab_final_bd/ip/Lab_final_bd_myip_v1_0_0_0/Lab_final_bd_myip_v1_0_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Lab_final_bd_myip_v1_0_0_0 || ORIG_REF_NAME==Lab_final_bd_myip_v1_0_0_0} -quiet] -quiet

# IP: bd/Lab_final_bd/ip/Lab_final_bd_processing_system7_0_0/Lab_final_bd_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Lab_final_bd_processing_system7_0_0 || ORIG_REF_NAME==Lab_final_bd_processing_system7_0_0} -quiet] -quiet

# IP: bd/Lab_final_bd/ip/Lab_final_bd_xbar_1/Lab_final_bd_xbar_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Lab_final_bd_xbar_1 || ORIG_REF_NAME==Lab_final_bd_xbar_1} -quiet] -quiet

# IP: bd/Lab_final_bd/ip/Lab_final_bd_auto_pc_1/Lab_final_bd_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Lab_final_bd_auto_pc_1 || ORIG_REF_NAME==Lab_final_bd_auto_pc_1} -quiet] -quiet

# IP: bd/Lab_final_bd/ip/Lab_final_bd_ps7_0_axi_periph_0/Lab_final_bd_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Lab_final_bd_ps7_0_axi_periph_0 || ORIG_REF_NAME==Lab_final_bd_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/Lab_final_bd/ip/Lab_final_bd_rst_ps7_0_50M_0/Lab_final_bd_rst_ps7_0_50M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Lab_final_bd_rst_ps7_0_50M_0 || ORIG_REF_NAME==Lab_final_bd_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/Lab_final_bd/ip/Lab_final_bd_blk_rom_weight_0/Lab_final_bd_blk_rom_weight_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Lab_final_bd_blk_rom_weight_0 || ORIG_REF_NAME==Lab_final_bd_blk_rom_weight_0} -quiet] -quiet

# IP: bd/Lab_final_bd/ip/Lab_final_bd_blk_rom_other_weight_0/Lab_final_bd_blk_rom_other_weight_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Lab_final_bd_blk_rom_other_weight_0 || ORIG_REF_NAME==Lab_final_bd_blk_rom_other_weight_0} -quiet] -quiet

# IP: bd/Lab_final_bd/ip/Lab_final_bd_blk_ram_temp_0/Lab_final_bd_blk_ram_temp_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Lab_final_bd_blk_ram_temp_0 || ORIG_REF_NAME==Lab_final_bd_blk_ram_temp_0} -quiet] -quiet

# IP: bd/Lab_final_bd/ip/Lab_final_bd_blk_rom_inimg_0/Lab_final_bd_blk_rom_inimg_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Lab_final_bd_blk_rom_inimg_0 || ORIG_REF_NAME==Lab_final_bd_blk_rom_inimg_0} -quiet] -quiet

# IP: bd/Lab_final_bd/ip/Lab_final_bd_ConV1_0_0/Lab_final_bd_ConV1_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Lab_final_bd_ConV1_0_0 || ORIG_REF_NAME==Lab_final_bd_ConV1_0_0} -quiet] -quiet

# IP: bd/Lab_final_bd/ip/Lab_final_bd_MP1_0_0/Lab_final_bd_MP1_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Lab_final_bd_MP1_0_0 || ORIG_REF_NAME==Lab_final_bd_MP1_0_0} -quiet] -quiet

# IP: bd/Lab_final_bd/ip/Lab_final_bd_MUX_mem_out_0_0/Lab_final_bd_MUX_mem_out_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Lab_final_bd_MUX_mem_out_0_0 || ORIG_REF_NAME==Lab_final_bd_MUX_mem_out_0_0} -quiet] -quiet

# IP: bd/Lab_final_bd/ip/Lab_final_bd_FC_0_0/Lab_final_bd_FC_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Lab_final_bd_FC_0_0 || ORIG_REF_NAME==Lab_final_bd_FC_0_0} -quiet] -quiet

# IP: bd/Lab_final_bd/ip/Lab_final_bd_MP2_0_0/Lab_final_bd_MP2_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Lab_final_bd_MP2_0_0 || ORIG_REF_NAME==Lab_final_bd_MP2_0_0} -quiet] -quiet

# XDC: c:/Users/Student/Desktop/Lab_final/lab_final_PLPS/lab_final.gen/sources_1/bd/Lab_final_bd/Lab_final_bd_ooc.xdc
