# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Lab_final/lab_final - test/lab_final.srcs/sources_1/bd/NN_bd/ip/NN_bd_blk_mem_gen_0_1/NN_bd_blk_mem_gen_0_1.xci
# IP: The module: 'NN_bd_blk_mem_gen_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Lab_final/lab_final - test/lab_final.gen/sources_1/bd/NN_bd/ip/NN_bd_blk_mem_gen_0_1/NN_bd_blk_mem_gen_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'NN_bd_blk_mem_gen_0_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Lab_final/lab_final - test/lab_final.srcs/sources_1/bd/NN_bd/ip/NN_bd_blk_mem_gen_0_1/NN_bd_blk_mem_gen_0_1.xci
# IP: The module: 'NN_bd_blk_mem_gen_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Lab_final/lab_final - test/lab_final.gen/sources_1/bd/NN_bd/ip/NN_bd_blk_mem_gen_0_1/NN_bd_blk_mem_gen_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'NN_bd_blk_mem_gen_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
